### ISSUE TITLE
Slack app for monitoring backend services

### ISSUE THREAD

**Issue by jmensch1** [hackforla/ops#1]
### Overview

When backend services go down, it would be convenient if the relevant team could be notified on Slack so they can address the issue.

### Action Items

- [ ] Create a Slack app with "incoming webhooks" enabled.
- [ ] For each team that wants to use the Slack app, create a webhook that's connected to the channel they want to receive notifications in.
- [ ] Each team can connect to their webhook from whatever backend services they're using. This would have to be done on a team-by-team basis.

### Resources/Instructions

These are the Slack instructions for creating an app with incoming webhooks. https://api.slack.com/messaging/webhooks

Note that our slack account is limited to 10 apps, and we've already got 10 installed. So in order for this to work, one of those other apps would have to be bumped.

**Comment by ExperimentsInHonesty** [comment]
VRMS already has a app installed.  We need to review this and update this app to take in webhooks and have a queue that processes messages, so that any  project at hfla can use it for any message its wants to send either on a schedule or one time.

**Comment by fyliu** [comment]
1. Looks like slackbot.js is using the send message api to send messages to a channel rather than going through a webhook.
https://github.com/hackforla/VRMS/blob/a4642fa7016ae0aff7a5c08a0c332b9538d3d903/backend/workers/slackbot.js#L51

2. It's actually incredibly easy to create a slackbot and add webhooks to it that make posts to specific channels. It's all clicking buttons on the slack website. I've done so and did the quick test in less than 10 mins including creating a new separate workspace to test it in. Just follow the instructions in the Resources link.

3. HfLA Projects will need to keep the webhook urls secret and can just post messages to them in order to have the messages appear in their channels.

4. We will have to get access to the VRMS app as collaborators if we don't want to bump that app off the workspace. I'm not sure if VRMS still uses the app. The code in their repo that uses the token isn't deployment-ready, although it looks like it would've worked at one point from a local instance of VRMS. The code hardcodes localhost:3000.

**Comment by fyliu** [comment]
I went to the VRMS meeting just now and got confirmation from David Rubinstein and the VRMS team that they are not using the slack app for anything. They agreed that it's okay to remove it and make a new one.

Next steps:
- [ ] make a list of projects that will use this app and their slack channel names
- [ ] remove the VRMS app unless someone still has access to it (disable, maybe at the same time as installing the new app)
- [ ] create a new app with webhooks to post messages to individual slack channels for the projects (app needs to be installed in the workspace before it has access to the channels to create webhooks)
- [ ] add collaborators from OPS who can update the app in case people leave HfLA
- [ ] create documentation on how to use the webhooks
- [ ] send the webhook url and documentation link to HfLA projects
- [ ] create documentation on how to update the slack app and the current list of collaborators who have access

**Comment by fyliu** [comment]
1. Progress - See above. The app is very easy to set up using the instructions in the Resources section
2. Blockers
 - Decision: make a new app or replace the VRMS one. I think it's easier to make a new app, unless we can find the person who created the VRMS app.
 - Permissions: need permissions to first install the new app into the slack workspace by kicking out the VRMS app. This connects the app to the slack channels so that the webhooks can be set up in the app.
 - Question: How to determine which slack channels to set up webhooks for? List of active projects somewhere?
4. Availability - An hour
5. ETA - An hour after the empty app is installed into hackforla slack workspace

**Comment by fyliu** [comment]
I stopped working on this and I've unassigned myself.

Here's my brain dump of where this left off.

Someone else seems to be working on the same thing over at VRMS although I can't find an issue for it on their issues tracker.

I had a slack conversation with Tim Shaker, I think in May, about his work on a similar or maybe the same slack app/bot we're talking about here. He replicated some VRMS tables like user, project, meeting and was going to generate reminder messages. This is roughly what I remember. It could be wrong.

Bonnie was at the VRMS meeting where I learned about Tim's work. I remember hearing a description of how the bot/app should work which is sort of an all in one messaging system for hackforla to volunteers and channels. I'm sure Bonnie was at that meeting and knows about Tim's work. I've heard about the slack bot design in both VRMS and OPS so I can't be certain where I've heard this.

**Comment by fyliu** [comment]
Somehow I'm not able to upload a screenshot right now, but here's the relevant VRMS message from May 16, 2022 about his slack app project that I'm still able to see:

[7:11 PM](https://hackforla.slack.com/archives/CRGH5HM0Q/p1652753501480449)
[Tim Shaker](https://app.slack.com/team/U018BJMQ79Q)
 You can try out the Slackbot in this Slack workspace:
https://join.slack.com/t/vrms-dev/shared_invite/zt-19286euad-hDHJhzR4vttlJryxz1Is2g (edited)

**Comment by fyliu** [comment]
Here is the issue where Tim is working on his Slack app https://github.com/100Automations/futureautomations/issues/8

**Comment by ExperimentsInHonesty** [comment]
closing this issue in favor of a new format for gathering requirements for a new bot platform https://github.com/hackforla/ops/issues/67
