### ISSUE TITLE
Review Current VRMS Slackbot Implementation

### ISSUE THREAD

**Issue by Neecolaa** [hackforla/ops#16]
### Overview
We need to do a deep dive on the existing VRMS slackbot.

### Action Items
- [ ] Create a list of files changed during slackbot PRs (add to Resources/Instructions)
- [x] Look through current code to figure out what it's doing
- [x] Contact VRMS team for information

### Resources/Instructions
Closed pull requests related to slackbot: https://github.com/hackforla/VRMS/pulls?q=is%3Apr+slackbot+is%3Aclosed+

**Comment by fyliu** [comment]
Looks like I should have commented on this issue rather than the other one. See that issue for reference.
- #1 

The quick summary
1. I went to some VRMS meetings and learned that they are no longer using their old slackbot that this issue is interested in.
1. The person who wrote it is also no longer with the project.
1. I did review the current code and it's not being called anymore. What it did was use the bot to send messages to slack users using their IDs. It's not actually using the slack app, but was calling the slack API from software.
1. During a later VRMS meeting, there was someone, Tim Shaker, who was working on a new slack app. It sounded like what we're trying to do in OPS. But if they're doing it in VRMS, there's no point in OPS finding out the implementation and working on another one, since there's only 1 remaining app slot in the free slack tier. 

I think we should close this issue. It's no longer relevant.
